version: '3'
services:
  zap2xml:
    image: watermark/zap2xml
    container_name: zap2xml
    restart: unless-stopped
    volumes:
      - zap2xml_data:/data
    environment:
      - USERNAME=username
      - PASSWORD=password
      - OPT_ARGS=-z -d 7
volumes:
  zap2xml_data:
