version: '3'

services:
  xmltv:
    image: zap2xml:latest
    restart: always
    ports:
      - "8080:80"
    environment:
        - USERNAME=myemail@email.com
        - PASSWORD=**password**
        - OPT_ARGS=-I -D
